name: 'Provision AKS'
on: workflow_dispatch

jobs:
  provision-aks:
    name: 'Deploy Terraform for AKS'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install kubectl
      run: |
        curl -LO https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl
        chmod +x kubectl
        mkdir -p ~/.local/bin
        mv ./kubectl ~/.local/bin/kubectl
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        kubectl version --client

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve

    - name: Configure kubectl for AKS
      run: |
        az aks get-credentials --resource-group aks-rg --name demo-aks --overwrite-existing
        kubectl get nodes
